name: Create reference manual and upload it to Github Page
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pdoc3
      
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Generate Reference Manual
        run: |
        pdoc3 --html --force --output-dir "docs" .

      - name: Deploy manual to Github Page https://qib-sheffield.github.io/MDR-Library/
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: master
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Reference Manual ${{ steps.date.outputs.date }}"